### ISSUE TITLE
Rename repo and get bundle-ready

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_Colorsys#13]
Repo should be renamed to be colorsys specific as this is the only library found within.

This library needs some love to be bundle-ready. Ideally we only have one .py file in root, and a requirement is that it imports the same way as in CPython.

There is no example - please add one.

@FoamyGuy I've assigned you to this issue. If you have questions along the way, feel free to ping me!

**Comment by jposada202020** [comment]
- https://github.com/adafruit/Adafruit_CircuitPython_FancyLED
- https://github.com/python/cpython/blob/3.9/Lib/colorsys.py

For reference... on more helpers avalaible

**Comment by dglaude** [comment]
To be compatible with CPython library, I would like such example to work:

https://github.com/pimoroni/blinkt/blob/master/examples/rainbow.py

This is how I learned to do rainbow:
```
import colorsys
# ...
        r, g, b = [int(c * 255) for c in colorsys.hsv_to_rgb(h, 1.0, 1.0)]
```

**Comment by jposada202020** [comment]
@kattni 
I think the new library is already release as of 
https://github.com/adafruit/Adafruit_CircuitPython_Colorsys

**Comment by kattni** [comment]
Yes this is done. Thanks for remembering the issue!
