### ISSUE TITLE
no rgb_to_hsv and Rob_to_hsb

### ISSUE THREAD

**Issue by LazaroFilm** [adafruit/Adafruit_CircuitPython_Colorsys#26]
This library is only 1/2 complete it can take hsb and hsv values to rub but not the other way around which renders it completely useless for my use. why such a big omission?

**Comment by tekktrik** [comment]
My guess is that CircuitPython seems to [prefer using the RGB colorspace](https://docs.circuitpython.org/en/latest/shared-bindings/displayio/index.html#displayio.Colorspace) regarding displaying things, so it only makes sense to define these one way to keep the file size smaller for smaller boards.

**Comment by FoamyGuy** [comment]
I've had a look around while working on some unrelated stuff for this library and didn't find any usages of it that are in the context of the smallest devices. 

I think it'd be fine to add more functions to this library that exist in the CPython implementation, but as noted by tekktrik, circuitpython teds to use primarily RGB so adding more isn't a priority for us. 

I'll close this issue, but if anyone would like to submit a PR adding more functions we will review.
